# maybe use an enum for this?

STATUS_CODE = {
    200: "200 OK",
    201: "201 Created",
    204: "204 No Content",
    301: "301 Moved Permanently",
    302: "302 Found",
    400: "400 Bad Request",
    401: "401 Unauthorized",
    403: "403 Forbidden",
    404: "404 Not Found",
    405: "405 Method Not Allowed",
    500: "500 Internal Server Error",
    503: "503 Service Unavailable",
}

# https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types/Common_types
MIME_TYPES = {
    ".html": "text/html",
    ".htm": "text/html",
    ".css": "text/css",
    ".js": "text/javascript",
    ".mjs": "text/javascript",
    ".json": "application/json",
    ".jsonld": "application/ld+json",
    ".xml": "application/xml",
    ".pdf": "application/pdf",
    ".txt": "text/plain",
    ".csv": "text/csv",
    ".png": "image/png",
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".svg": "image/svg+xml",
    ".ico": "image/vnd.microsoft.icon",
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".mp4": "video/mp4",
    ".mpeg": "video/mpeg",
    ".webm": "video/webm",
    ".zip": "application/zip",
    ".rar": "application/vnd.rar",
    ".7z": "application/x-7z-compressed",
    ".tar": "application/x-tar",
    ".doc": "application/msword",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".xls": "application/vnd.ms-excel",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".ppt": "application/vnd.ms-powerpoint",
    ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".otf": "font/otf",
    ".ttf": "font/ttf",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".bin": "application/octet-stream"
}

SERVED_HEADER_FIELDS = frozenset([
    "accept",
    "accept-charset",
    "accept-encoding",
    "accept-language",
    "accept-ranges",    
    "connection",
    "content-length",
    "content-encoding",
    "content-language",
    "content-range",
    "content-type",
    "date",
    "expect",
    "host",
    "last-modified", 
    "user-agent", 
    "www-authenticate"
])

CORRECT_HEADER_FIELDS = frozenset([
    "age", 
    "allow", # thats a server response header, no meaning for request
    "authorization",
    "cache-control",
    "content-location",
    "content-md5",
    "etag",
    "expires",
    "from",
    "if-match",
    "if-modified-since",
    "if-range",
    "location", 
    "max-forwards",
    "pragma",
    "proxy-authenticate",
    "proxy-authorization",
    "range",
    "refer",
    "retry-after", 
    "server", 
    "te",  
    "trailer", 
    "transfer-encoding", 
    "upgrade", 
    "vary", 
    "via", 
    "warning", 
])

METHODS = [
    "GET",
    "HEAD",
    "POST",
    "PUT",
    "PATCH",
    "DELETE"
]